### ISSUE TITLE
how to run it ?Many files does not exist！hope u help me！

### ISSUE THREAD

**Issue by whereitogo** [beratkurar/textline_segmentation_using_fcn#2]

**Comment by beratkurar** [comment]
Please specify which file does not exist?

**Comment by whereitogo** [comment]
> Please specify which file does not exist?

there is no "vgg.h5" file.I downloaded file from "https://github.com/fchollet/deep-learning-models/releases/download/v0.1/vgg16_weights_th_dim_ordering_th_kernels.h5",but cannt run @beratkurar

**Comment by beratkurar** [comment]
Github limits the size of files that can be uploaded. Therefore I am not able to upload it to the repository.

**Comment by whereitogo** [comment]
> Github limits the size of files that can be uploaded. Therefore I am not able to upload it to the repository.
Would u mind provided some advice for me  about the problem?
 whats the dataset? What are the parameters of the network？（vgg.h5）

**Comment by beratkurar** [comment]
Here is the paper:
https://www.cs.bgu.ac.il/~berat/papers/Icfhr2018Text.pdf
